apiVersion: v1
kind: Service
metadata:
  name: ${env_name}-proxy
  labels:
    app.kubernetes.io/name: proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: proxy