apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: default
  labels:
    app: tomcat
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tomcat
        tier: backend
    spec:
      containers:
        - name: tomcat
          image: tomcat:9.0-jdk11
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgres-service.default.svc.cluster.local:5432"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres_password"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 15
